/**
 * Emotion taxonomy — 15 categories across 3 progressive tiers.
 *
 * Tier 1: Ekman's basic 7 — foundation
 * Tier 2: Confusable pairs — what separates emotions that look alike
 * Tier 3: Mixed / suppressed — micro-expressions, masking, contradiction
 *
 * The `analysis` field is populated from emotions_analysis.json, which is
 * generated by extracting the NotebookLM Face notebook report (Велховер +
 * Лафатер + Хигир + Экман synthesis). See scripts/extract-knowledge.ts.
 */

import analyses from './emotions_analysis.json';
const ANALYSES = analyses as Record<string, string>;

export type EmotionId =
  // tier 1 — basic
  | 'joy'
  | 'sadness'
  | 'anger'
  | 'fear'
  | 'surprise'
  | 'disgust'
  | 'contempt'
  // tier 2 — distinguishing pairs
  | 'duchenne_smile'
  | 'social_smile'
  | 'fear_vs_surprise_F'
  | 'fear_vs_surprise_S'
  | 'controlled_anger'
  | 'sadness_vs_fatigue_S'
  | 'sadness_vs_fatigue_F'
  | 'shame'
  | 'guilt'
  // tier 3 — mixed / suppressed
  | 'nostalgia'
  | 'suppressed_anger'
  | 'anxiety';

export type Tier = 1 | 2 | 3;

export interface EmotionMeta {
  id: EmotionId;
  tier: Tier;
  ru: string;
  short: string;
  /** Other emotions commonly confused with this one — used for distractor MCQ options. */
  confusedWith: EmotionId[];
  /** Detailed analysis text shown after the user answers. Populated from NotebookLM. */
  analysis: string;
  /** Specific FACS Action Units / facial markers the user should have spotted. */
  markers: string[];
}

export const EMOTIONS: Record<EmotionId, EmotionMeta> = {
  joy: {
    id: 'joy',
    tier: 1,
    ru: 'Радость (искренняя)',
    short: 'Искренняя радость с задействованной круговой мышцей глаза',
    confusedWith: ['social_smile'],
    analysis: '',
    markers: ['AU6 — поднятие щёк', 'AU12 — поднятие уголков губ', 'Морщины-«гусиные лапки» у глаз'],
  },
  sadness: {
    id: 'sadness',
    tier: 1,
    ru: 'Грусть',
    short: 'Опущенные веки, внутренние края бровей подняты',
    confusedWith: ['sadness_vs_fatigue_F', 'shame'],
    analysis: '',
    markers: ['AU1 — поднятие внутренних углов бровей', 'AU4 — сведение бровей', 'AU15 — опущение уголков губ'],
  },
  anger: {
    id: 'anger',
    tier: 1,
    ru: 'Гнев',
    short: 'Сведённые брови, напряжённые губы, расширенные ноздри',
    confusedWith: ['contempt', 'controlled_anger'],
    analysis: '',
    markers: ['AU4 — сведение бровей', 'AU5 — поднятие верхнего века', 'AU23 — напряжение губ', 'AU7 — напряжение нижнего века'],
  },
  fear: {
    id: 'fear',
    tier: 1,
    ru: 'Страх',
    short: 'Поднятые и сведённые брови, растянутые губы',
    confusedWith: ['surprise', 'anxiety'],
    analysis: '',
    markers: ['AU1+AU2+AU4 — комбинированное поднятие бровей с напряжением', 'AU5 — расширенные глаза', 'AU20 — растянутые губы'],
  },
  surprise: {
    id: 'surprise',
    tier: 1,
    ru: 'Удивление',
    short: 'Поднятые брови, открытый рот, расширенные глаза',
    confusedWith: ['fear'],
    analysis: '',
    markers: ['AU1+AU2 — поднятие всей линии бровей', 'AU5 — поднятие верхнего века', 'AU26 — отвисание челюсти'],
  },
  disgust: {
    id: 'disgust',
    tier: 1,
    ru: 'Отвращение',
    short: 'Сморщенный нос, поднятая верхняя губа',
    confusedWith: ['contempt'],
    analysis: '',
    markers: ['AU9 — сморщивание носа', 'AU10 — поднятие верхней губы', 'AU17 — поднятие подбородка'],
  },
  contempt: {
    id: 'contempt',
    tier: 1,
    ru: 'Презрение',
    short: 'Односторонняя усмешка — единственная асимметричная базовая эмоция',
    confusedWith: ['disgust', 'controlled_anger'],
    analysis: '',
    markers: ['AU14 — одностороннее напряжение уголка губ', 'Лёгкое поднятие одной щеки'],
  },

  duchenne_smile: {
    id: 'duchenne_smile',
    tier: 2,
    ru: 'Дюшенновская (искренняя) улыбка',
    short: 'Улыбка с участием мышц вокруг глаз — невозможно подделать сознательно',
    confusedWith: ['social_smile'],
    analysis: '',
    markers: ['AU6 — поднятие щёк, морщины у внешних углов глаз', 'AU12 — симметричное поднятие уголков губ', 'Прищур глаз'],
  },
  social_smile: {
    id: 'social_smile',
    tier: 2,
    ru: 'Социальная (вежливая) улыбка',
    short: 'Улыбка только губами, глаза не задействованы',
    confusedWith: ['duchenne_smile'],
    analysis: '',
    markers: ['AU12 без AU6', 'Глаза остаются спокойными, без морщин', 'Часто асимметрия или быстрый «выход» из улыбки'],
  },
  fear_vs_surprise_F: {
    id: 'fear_vs_surprise_F',
    tier: 2,
    ru: 'Страх (отличие от удивления)',
    short: 'Брови подняты И сведены — индикатор страха, не удивления',
    confusedWith: ['surprise'],
    analysis: '',
    markers: ['AU1+AU2+AU4 — поднятие бровей с одновременным сведением', 'Растянутые в стороны губы (AU20)', 'Удерживается дольше, чем удивление'],
  },
  fear_vs_surprise_S: {
    id: 'fear_vs_surprise_S',
    tier: 2,
    ru: 'Удивление (отличие от страха)',
    short: 'Брови ровно подняты без сведения, рот открыт расслабленно',
    confusedWith: ['fear'],
    analysis: '',
    markers: ['AU1+AU2 без AU4', 'Открытый, расслабленный рот (AU26)', 'Микро-вспышка — длится менее секунды'],
  },
  controlled_anger: {
    id: 'controlled_anger',
    tier: 2,
    ru: 'Контролируемый/подавленный гнев',
    short: 'Сжатая челюсть, напряжённые губы, прямой холодный взгляд',
    confusedWith: ['contempt', 'anger'],
    analysis: '',
    markers: ['AU23+AU24 — прижатые и поджатые губы', 'Напряжение жевательных мышц (видны желваки)', 'Прямой неподвижный взгляд', 'Раздувающиеся ноздри'],
  },
  sadness_vs_fatigue_S: {
    id: 'sadness_vs_fatigue_S',
    tier: 2,
    ru: 'Грусть (отличие от усталости)',
    short: 'Поднятые внутренние края бровей — ключевой маркер грусти',
    confusedWith: ['sadness_vs_fatigue_F'],
    analysis: '',
    markers: ['AU1 — внутренние края бровей подняты', 'Опущенные уголки губ (AU15)', 'Взгляд направлен вниз/в себя'],
  },
  sadness_vs_fatigue_F: {
    id: 'sadness_vs_fatigue_F',
    tier: 2,
    ru: 'Усталость / разочарование (отличие от грусти)',
    short: 'Тяжёлые веки, опущенные щёки, но брови нейтральны',
    confusedWith: ['sadness_vs_fatigue_S'],
    analysis: '',
    markers: ['Тяжёлые верхние веки', 'Расслабленные мышцы лица', 'AU1 НЕ задействован — внутренние брови ровные', 'Общая «опущенность» без специфики'],
  },
  shame: {
    id: 'shame',
    tier: 2,
    ru: 'Стыд',
    short: 'Опущенный взгляд, повёрнутая голова, прикрытие лица',
    confusedWith: ['guilt', 'sadness'],
    analysis: '',
    markers: ['Опущенная голова и взгляд', 'Покраснение лица (если видно)', 'Часто прикрытие лица или его части рукой', 'Уменьшение себя в позе'],
  },
  guilt: {
    id: 'guilt',
    tier: 2,
    ru: 'Вина',
    short: 'Удержание зрительного контакта, но напряжение в нижней части лица',
    confusedWith: ['shame'],
    analysis: '',
    markers: ['Зрительный контакт сохраняется (в отличие от стыда)', 'Сжатые или закусанные губы', 'Лёгкое сведение бровей', 'Поза собранная, не съёженная'],
  },

  nostalgia: {
    id: 'nostalgia',
    tier: 3,
    ru: 'Ностальгия / горько-сладкое',
    short: 'Лёгкая улыбка с поднятыми внутренними бровями (грусть + радость)',
    confusedWith: ['sadness', 'joy'],
    analysis: '',
    markers: ['AU1 — внутренние края бровей подняты (грусть)', 'AU12 — лёгкое поднятие уголков губ (улыбка)', 'Расфокусированный взгляд', 'Часто отсутствие AU6 — улыбка не доходит до глаз'],
  },
  suppressed_anger: {
    id: 'suppressed_anger',
    tier: 3,
    ru: 'Подавленный гнев под маской нейтральности',
    short: 'Лицо нейтральное, но микро-маркеры напряжения выдают',
    confusedWith: ['controlled_anger', 'contempt'],
    analysis: '',
    markers: ['Напряжение в зоне AU4 (между бровями) — даже без явного сведения', 'Прижатые губы (AU24) при «нейтральном» лице', 'Напряжение жевательных мышц', 'Холодный, фиксированный взгляд'],
  },
  anxiety: {
    id: 'anxiety',
    tier: 3,
    ru: 'Тревога (страх + грусть)',
    short: 'Маркеры страха в верхней части лица + маркеры грусти в нижней',
    confusedWith: ['fear', 'sadness'],
    analysis: '',
    markers: ['AU1+AU2+AU4 в зоне бровей (страх)', 'AU15 — опущенные уголки губ (грусть)', 'Беспокойный, бегающий взгляд', 'Часто прикусывание губы'],
  },
};

export const TIER_TITLES: Record<Tier, string> = {
  1: 'Базовые эмоции',
  2: 'Различительные пары',
  3: 'Смешанные и подавленные',
};

// Merge analyses from JSON into the EMOTIONS map at module init.
for (const [id, text] of Object.entries(ANALYSES)) {
  if (EMOTIONS[id as EmotionId]) {
    EMOTIONS[id as EmotionId].analysis = text;
  }
}

export function emotionsByTier(tier: Tier): EmotionMeta[] {
  return Object.values(EMOTIONS).filter((e) => e.tier === tier);
}
